//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.API.Netspeed.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.API.Netspeed.Localization.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Automatic Payment.
        /// </summary>
        public static string ActivateAutomaticPayment {
            get {
                return ResourceManager.GetString("ActivateAutomaticPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        public static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Code.
        /// </summary>
        public static string AddressCode {
            get {
                return ResourceManager.GetString("AddressCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Infrastructure Query.
        /// </summary>
        public static string AddressInfrastructureQuery {
            get {
                return ResourceManager.GetString("AddressInfrastructureQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Support Requests.
        /// </summary>
        public static string AllSupportRequests {
            get {
                return ResourceManager.GetString("AllSupportRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Payment.
        /// </summary>
        public static string AutomaticPayment {
            get {
                return ResourceManager.GetString("AutomaticPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Payment Subscriptions.
        /// </summary>
        public static string AutomaticPaymentSubscriptions {
            get {
                return ResourceManager.GetString("AutomaticPaymentSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Speed.
        /// </summary>
        public static string AvailabilityMaxSpeed {
            get {
                return ResourceManager.GetString("AvailabilityMaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Site.
        /// </summary>
        public static string BackToSite {
            get {
                return ResourceManager.GetString("BackToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting to the bank, please wait....
        /// </summary>
        public static string BankRedirectWaitMessage {
            get {
                return ResourceManager.GetString("BankRedirectWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills and Payments.
        /// </summary>
        public static string BillsAndPayments {
            get {
                return ResourceManager.GetString("BillsAndPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Me.
        /// </summary>
        public static string CallMe {
            get {
                return ResourceManager.GetString("CallMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your call me request has been received..
        /// </summary>
        public static string CallMeRequestCompleted {
            get {
                return ResourceManager.GetString("CallMeRequestCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will call you so that we can offer you the appropriate internet tariff..
        /// </summary>
        public static string CallMeTitle {
            get {
                return ResourceManager.GetString("CallMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Call You.
        /// </summary>
        public static string CallYou {
            get {
                return ResourceManager.GetString("CallYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha does not match..
        /// </summary>
        public static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholder Name.
        /// </summary>
        public static string CardholderName {
            get {
                return ResourceManager.GetString("CardholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Credit Cards.
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This credit card has active automatic payments. To remove this please cancel the automatic payment..
        /// </summary>
        public static string CardWithActiveAutoPayment {
            get {
                return ResourceManager.GetString("CardWithActiveAutoPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Apartment.
        /// </summary>
        public static string ChooseApartment {
            get {
                return ResourceManager.GetString("ChooseApartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Building.
        /// </summary>
        public static string ChooseBuilding {
            get {
                return ResourceManager.GetString("ChooseBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose District.
        /// </summary>
        public static string ChooseDistrict {
            get {
                return ResourceManager.GetString("ChooseDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Neighborhood.
        /// </summary>
        public static string ChooseNeighborhood {
            get {
                return ResourceManager.GetString("ChooseNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Province.
        /// </summary>
        public static string ChooseProvince {
            get {
                return ResourceManager.GetString("ChooseProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Region.
        /// </summary>
        public static string ChooseRegion {
            get {
                return ResourceManager.GetString("ChooseRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Street.
        /// </summary>
        public static string ChooseStreet {
            get {
                return ResourceManager.GetString("ChooseStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name/Company Title.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please try again..
        /// </summary>
        public static string ClientNotFound {
            get {
                return ResourceManager.GetString("ClientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Status.
        /// </summary>
        public static string ConnectionStatus {
            get {
                return ResourceManager.GetString("ConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Netspeed İnternet A.Ş &amp;nbsp;|&amp;nbsp; &lt;a href=&quot;https://www.netspeed.com.tr&quot; title=&quot;Netspeed&quot; target=&quot;_blank&quot;&gt;www.netspeed.com.tr&lt;/a&gt;.
        /// </summary>
        public static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        public static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Automatic Payment.
        /// </summary>
        public static string DeactivateAutomaticPayment {
            get {
                return ResourceManager.GetString("DeactivateAutomaticPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe support request..
        /// </summary>
        public static string DescribeSupportRequest {
            get {
                return ResourceManager.GetString("DescribeSupportRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount amount.
        /// </summary>
        public static string DiscountAmount {
            get {
                return ResourceManager.GetString("DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Noise Margin.
        /// </summary>
        public static string DownloadNoiseMargin {
            get {
                return ResourceManager.GetString("DownloadNoiseMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Noise Margin.
        /// </summary>
        public static string DownloadUploadMargin {
            get {
                return ResourceManager.GetString("DownloadUploadMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Archive PDF.
        /// </summary>
        public static string EArchivePDF {
            get {
                return ResourceManager.GetString("EArchivePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Archive PDF.
        /// </summary>
        public static string EArchivePDFFileName {
            get {
                return ResourceManager.GetString("EArchivePDFFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during operation, please contact our support..
        /// </summary>
        public static string ErrorPleaseContact {
            get {
                return ResourceManager.GetString("ErrorPleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string ExpirationDateMonth {
            get {
                return ResourceManager.GetString("ExpirationDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string ExpirationDateMonthPlaceHolder {
            get {
                return ResourceManager.GetString("ExpirationDateMonthPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string ExpirationDateYear {
            get {
                return ResourceManager.GetString("ExpirationDateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yy.
        /// </summary>
        public static string ExpirationDateYearPlaceHolder {
            get {
                return ResourceManager.GetString("ExpirationDateYearPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Packet.
        /// </summary>
        public static string ExtendPacket {
            get {
                return ResourceManager.GetString("ExtendPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Download.
        /// </summary>
        public static string FUPDownload {
            get {
                return ResourceManager.GetString("FUPDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Upload.
        /// </summary>
        public static string FUPUpload {
            get {
                return ResourceManager.GetString("FUPUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Please contact our support team..
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General State.
        /// </summary>
        public static string GeneralState {
            get {
                return ResourceManager.GetString("GeneralState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an active support request. Can not send a new one..
        /// </summary>
        public static string HasActiveRequest {
            get {
                return ResourceManager.GetString("HasActiveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquire Again.
        /// </summary>
        public static string InquireAgain {
            get {
                return ResourceManager.GetString("InquireAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Address.
        /// </summary>
        public static string InstallationAddress {
            get {
                return ResourceManager.GetString("InstallationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string InternalErrorDescription {
            get {
                return ResourceManager.GetString("InternalErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Access Password.
        /// </summary>
        public static string InternetPassword {
            get {
                return ResourceManager.GetString("InternetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Access Username.
        /// </summary>
        public static string InternetUsername {
            get {
                return ResourceManager.GetString("InternetUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token!.
        /// </summary>
        public static string InvalidTokenKey {
            get {
                return ResourceManager.GetString("InvalidTokenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should your request be marked as my problem solved?.
        /// </summary>
        public static string IsMarkedRequestSolved {
            get {
                return ResourceManager.GetString("IsMarkedRequestSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 Periods Usage Report.
        /// </summary>
        public static string Last3PeriodsUsage {
            get {
                return ResourceManager.GetString("Last3PeriodsUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Payment Date.
        /// </summary>
        public static string LastPaymentDate {
            get {
                return ResourceManager.GetString("LastPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn Your Address Code.
        /// </summary>
        public static string LearnAddressCode {
            get {
                return ResourceManager.GetString("LearnAddressCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINE STATE.
        /// </summary>
        public static string LineState {
            get {
                return ResourceManager.GetString("LineState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM No or TCK No.
        /// </summary>
        public static string LoginCustomerCode {
            get {
                return ResourceManager.GetString("LoginCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent SMS Password.
        /// </summary>
        public static string LoginSMSPassword {
            get {
                return ResourceManager.GetString("LoginSMSPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        public static string MaskedCardNo {
            get {
                return ResourceManager.GetString("MaskedCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed.
        /// </summary>
        public static string MissedCount {
            get {
                return ResourceManager.GetString("MissedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        public static string MyDocuments {
            get {
                return ResourceManager.GetString("MyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new notification.
        /// </summary>
        public static string NewNotification {
            get {
                return ResourceManager.GetString("NewNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Support Request.
        /// </summary>
        public static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can request support and follow up..
        /// </summary>
        public static string NewRequestDescription {
            get {
                return ResourceManager.GetString("NewRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can we help you?.
        /// </summary>
        public static string NewSupportRequest {
            get {
                return ResourceManager.GetString("NewSupportRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightly Download.
        /// </summary>
        public static string NonFUPDownload {
            get {
                return ResourceManager.GetString("NonFUPDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightly Upload.
        /// </summary>
        public static string NonFUPUpload {
            get {
                return ResourceManager.GetString("NonFUPUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are updating... Please retry in 10 minutes..
        /// </summary>
        public static string NotAvailableDescription {
            get {
                return ResourceManager.GetString("NotAvailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid {0}..
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Request Again.
        /// </summary>
        public static string OpenRequestAgain {
            get {
                return ResourceManager.GetString("OpenRequestAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your customer website password is {0}..
        /// </summary>
        public static string PasswordSMS {
            get {
                return ResourceManager.GetString("PasswordSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay All.
        /// </summary>
        public static string PayAll {
            get {
                return ResourceManager.GetString("PayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed.
        /// </summary>
        public static string Payed {
            get {
                return ResourceManager.GetString("Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select how you want to pay..
        /// </summary>
        public static string PaymentSelection {
            get {
                return ResourceManager.GetString("PaymentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve credit cards. Please try again later..
        /// </summary>
        public static string PaymentWithCardNotAvailable {
            get {
                return ResourceManager.GetString("PaymentWithCardNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Now.
        /// </summary>
        public static string PayNow {
            get {
                return ResourceManager.GetString("PayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with another card.
        /// </summary>
        public static string PayWithOtherCards {
            get {
                return ResourceManager.GetString("PayWithOtherCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        public static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing...Please Wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Available.
        /// </summary>
        public static string PortAvailable {
            get {
                return ResourceManager.GetString("PortAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Not Availabe.
        /// </summary>
        public static string PortNotAvailable {
            get {
                return ResourceManager.GetString("PortNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port State.
        /// </summary>
        public static string PortState {
            get {
                return ResourceManager.GetString("PortState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment successful..
        /// </summary>
        public static string POSSuccessMessage {
            get {
                return ResourceManager.GetString("POSSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Is Solved.
        /// </summary>
        public static string ProblemSolved {
            get {
                return ResourceManager.GetString("ProblemSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSTN.
        /// </summary>
        public static string PSTN {
            get {
                return ResourceManager.GetString("PSTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Query.
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Pakages.
        /// </summary>
        public static string QuotaPakages {
            get {
                return ResourceManager.GetString("QuotaPakages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting....
        /// </summary>
        public static string Redirecting {
            get {
                return ResourceManager.GetString("Redirecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;You have an active subscription.&lt;/div&gt; You can submit your request through the &lt;span&gt;Customer Service &lt;/span&gt;. You are being redirected to the Customer Service ....
        /// </summary>
        public static string RedirectPageTitle {
            get {
                return ResourceManager.GetString("RedirectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        public static string ReferenceNo {
            get {
                return ResourceManager.GetString("ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New register password is {0}.
        /// </summary>
        public static string RegisterSMS {
            get {
                return ResourceManager.GetString("RegisterSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string RemainingCount {
            get {
                return ResourceManager.GetString("RemainingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMAINING FUP.
        /// </summary>
        public static string RemainingFUP {
            get {
                return ResourceManager.GetString("RemainingFUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Card.
        /// </summary>
        public static string RemoveCard {
            get {
                return ResourceManager.GetString("RemoveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select support description type.
        /// </summary>
        public static string SelectionSupportSubType {
            get {
                return ResourceManager.GetString("SelectionSupportSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Support Request.
        /// </summary>
        public static string SendSupportRequest {
            get {
                return ResourceManager.GetString("SendSupportRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service(s).
        /// </summary>
        public static string Service_Services {
            get {
                return ResourceManager.GetString("Service_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Services.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please check your password..
        /// </summary>
        public static string SMSPasswordWrong {
            get {
                return ResourceManager.GetString("SMSPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is sent via SMS. This password can be used for {0} hours..
        /// </summary>
        public static string SMSWarningMessage {
            get {
                return ResourceManager.GetString("SMSWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Special Offers.
        /// </summary>
        public static string SpecialOffers {
            get {
                return ResourceManager.GetString("SpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber No.
        /// </summary>
        public static string SubscriberNo {
            get {
                return ResourceManager.GetString("SubscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber not found!.
        /// </summary>
        public static string SubscriberNotFound {
            get {
                return ResourceManager.GetString("SubscriberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber State.
        /// </summary>
        public static string SubscriberState {
            get {
                return ResourceManager.GetString("SubscriberState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see your other subscriptions from here..
        /// </summary>
        public static string SubscriptionInformationTitle {
            get {
                return ResourceManager.GetString("SubscriptionInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support and Requests.
        /// </summary>
        public static string SupportAndRequests {
            get {
                return ResourceManager.GetString("SupportAndRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Details.
        /// </summary>
        public static string SupportDetails {
            get {
                return ResourceManager.GetString("SupportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Request Approval.
        /// </summary>
        public static string SupportRequestApproval {
            get {
                return ResourceManager.GetString("SupportRequestApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your message..
        /// </summary>
        public static string SupportRequestMessage {
            get {
                return ResourceManager.GetString("SupportRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query No.
        /// </summary>
        public static string SVUID {
            get {
                return ResourceManager.GetString("SVUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff and Trafic.
        /// </summary>
        public static string TariffAndTraffic {
            get {
                return ResourceManager.GetString("TariffAndTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Period.
        /// </summary>
        public static string ThisPeriod {
            get {
                return ResourceManager.GetString("ThisPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned.
        /// </summary>
        public static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total (Discount Quantity).
        /// </summary>
        public static string TotalDiscountCount {
            get {
                return ResourceManager.GetString("TotalDiscountCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Downoald.
        /// </summary>
        public static string TotalDownload {
            get {
                return ResourceManager.GetString("TotalDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL FUP.
        /// </summary>
        public static string TotalFUP {
            get {
                return ResourceManager.GetString("TotalFUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalUpload.
        /// </summary>
        public static string TotalUpload {
            get {
                return ResourceManager.GetString("TotalUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service No.
        /// </summary>
        public static string TTSubscriberNo {
            get {
                return ResourceManager.GetString("TTSubscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have &lt;span class=&quot;bold&quot;&gt;{0}&lt;/span&gt; unpaid invoices with total of &lt;span class=&quot;bold&quot;&gt;{1}&lt;/span&gt;. If you wish, you can pay immediately with your credit card..
        /// </summary>
        public static string UnpaidBillsMessage {
            get {
                return ResourceManager.GetString("UnpaidBillsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Noise Margin.
        /// </summary>
        public static string UploadNoiseMargin {
            get {
                return ResourceManager.GetString("UploadNoiseMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string UsedCount {
            get {
                return ResourceManager.GetString("UsedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Bills.
        /// </summary>
        public static string ViewAllBills {
            get {
                return ResourceManager.GetString("ViewAllBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEAR &lt;span class=&quot;welcome-message&quot;&gt;{0}&lt;/span&gt; WELCOME.
        /// </summary>
        public static string WelcomeMessageHeader {
            get {
                return ResourceManager.GetString("WelcomeMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0} Online Services, you can pay your invoice instantly with a credit card and you can perform more transactions 24/7 fast and safely..
        /// </summary>
        public static string WelcomeMessageText {
            get {
                return ResourceManager.GetString("WelcomeMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
